'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
module.exports = [
  'aggregateData',
  'button',
  'calendar',
  'chart',
  'checkbox',
  'container',
  'input',
  'link',
  'vpagination',
  'pagination',
  'processor',
  'progress',
  'querybuilder',
  'radio',
  'resourceMark',
  'richtext',
  'schedule',
  'select',
  'tab',
  'table',
  'tag',
  'text',
  'textarea',
  'tree',
  'upload',
  'flow',
];
